apiVersion: v1
kind: Service
metadata:
  name: $PROJECT_NAME
  namespace: $NAMESPACE
spec:
  ports:
  - name: guestbook-port
    nodePort: $NODEPORT 
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: $PROJECT_NAME
  type: NodePort